on:
  push:
    branches:
    - master
    
name: OpenAPI Specs lint

jobs:
  build:
    name: Spectral checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stoplightio/spectral-action@latest
        with:
          file_glob: './*/*.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CI_TOKEN }}
